-- Deploy citybikes:journeys to pg
-- requires: stations
BEGIN;

CREATE TABLE internal.journeys(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    departure_time TIMESTAMPTZ NOT NULL,
    return_time TIMESTAMP NOT NULL,
    departure_station_id INTEGER REFERENCES internal.stations(id),
    return_station_id INTEGER REFERENCES internal.stations(id),
    distance_in_meters INTEGER NOT NULL,
    CONSTRAINT not_less_than_ten_meters CHECK (distance_in_meters >= 10),
    CONSTRAINT not_less_than_ten_seconds CHECK (return_time - departure_time >= INTERVAL '10 seconds')
);

COMMIT;

